### ISSUE TITLE
Is the MVVM sample app finished?

### ISSUE THREAD

**Issue by mrtj** [sunshinejr/Kittygram#1]
Because I have an impression it isn't 😿

**Comment by sunshinejr** [comment]
Hey @mrtj, are you talking about [this branch](https://github.com/sunshinejr/Kittygram/tree/mvvmc)? If that's correct, please let me know what would you like to see.

**Comment by mrtj** [comment]
Sorry for the vague issue description, now I understood better the structure of the app. However for some reason selecting a repo on the dashboard table view does not trigger a push of the details view controller when I build the app (Xcode 8, iOS 10.2). I did not find the cause of this bug.

**Comment by mrtj** [comment]
Yes, talking about the mvvmc branch

**Comment by sunshinejr** [comment]
Oh, it _should_ work (at least it worked few months ago). Sorry for that, will check it ASAP.

**Comment by markkrenek** [comment]
There are several issues:

(1) DashboardViewModel.delegate is never getting set. Line 14 in DashboardCoordinator should be `let viewModel = DashboardViewModel(delegate: self)`. BTW, the file names PayMoneyPleaseCoordinator.swift and DashboardCoordinator.swift are reversed.

(2) The AppCoordinator created in AppDelegate is not being retained – AppDelegate.coordinator needs to be set. So all the coordinators are actually getting released right after being created.

**Comment by sunshinejr** [comment]
Hey guys, I've fixed the issues with mvvmc branch. Although I feel like this isn't full example, I don't have the correct version anywhere on my disk. That being said, I will open a new issue with extending the app with more examples/more content. Thanks for the help again! 🙇

**Comment by Sadmansamee** [comment]
any update on this?
