### ISSUE TITLE
why childCoordinators.append(coordinator)

### ISSUE THREAD

**Issue by AppHock** [sunshinejr/Kittygram#5]
childCoordinators.append(coordinator) 
This code was deleted by me and works the same.

**Comment by sunshinejr** [comment]
Hey @AppHock, sorry for the late reply. Basically you have to retain the child coordinator somehow, as everyone keeps it as a weak reference (deegates). 

It will work just fine if you only want to start a new coordinator. However, if you pass it to the VM as a delegate, it won’t handle any events as it will be deallocated quickly after the method that spawns it finishes executing.
