### ISSUE TITLE
Needs Several Changes to work in Swift 4.1

### ISSUE THREAD

**Issue by StephenClarkApps** [sunshinejr/Kittygram#6]
A working example in Swift 4.1 could be cool - these could be made on separate branches for the before and after if wishing to preserve the original source on the main branches.

**Comment by sunshinejr** [comment]
Hey @StephenClarkApps. Yeah, it would be great, unfortunately I don't really have time to do it. If anyone would be interested in updating Swift version here (may be even to 5.0) I would really appreciate it.

**Comment by shengyang998** [comment]
code is now converted to support swift 5.0 #7
